-- Opción optimizada: Solo borra datos y reinicia contadores
DELETE FROM DISPOSITIVOS;
DELETE FROM TITULARES;

ALTER TABLE DISPOSITIVOS ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE TITULARES ALTER COLUMN ID RESTART WITH 1;