# Dispositivos
label.dispositivo.empty=No se han encontrado dispositivos
label.dispositivo.marca=Marca
label.dispositivo.modelo=Modelo
label.dispositivo.fabricante=Detalle del fabricante del dispositivo
dispositivos.search=Buscar

# Barra de navegaci�n
nav.home=Inicio
nav.login=Conexión
nav.logout=Cerrar Sesión
nav.new.dispositivos=Nuevo Dispositivo
error.404=Recurso no encontrado

# Autenticaci�n
auth.login=Iniciar Sesión
auth.register=Registrarse
auth.logout=Cerrar Sesión
auth.email=Email
auth.username=Usuario
auth.password=Contraseña
auth.remember=Recordarme
auth.forgot.password=Olvidaste tu contraseña?