-- Borra las tablas si existen
DROP TABLE IF EXISTS DISPOSITIVOS;
DROP TABLE IF EXISTS TITULARES;

-- Crea la tabla TITULARES (primero porque es la 'padre' de la relación)
CREATE TABLE TITULARES (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(20) NOT NULL UNIQUE,
                           is_deleted BOOLEAN DEFAULT FALSE,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Borra las tablas si existen
DROP TABLE IF EXISTS DISPOSITIVOS;
DROP TABLE IF EXISTS TITULARES;

-- Crea la tabla TITULARES (primero porque es la 'padre' de la relación)
CREATE TABLE TITULARES (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre VARCHAR(20) NOT NULL UNIQUE,
                           is_deleted BOOLEAN DEFAULT FALSE,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Crea la tabla DISPOSITIVOS
CREATE TABLE DISPOSITIVOS (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              marca VARCHAR(20) NOT NULL,
                              modelo VARCHAR(20) NOT NULL,
                              numero_serie VARCHAR(100) NOT NULL,
                              fabricante VARCHAR(32) NOT NULL,
                              tipo VARCHAR(20) NOT NULL,
                              titular_id BIGINT,
                              is_deleted BOOLEAN DEFAULT FALSE,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              uuid UUID NOT NULL UNIQUE
);

-- Añade la restricción de clave foránea
ALTER TABLE IF EXISTS DISPOSITIVOS
    ADD CONSTRAINT fk_dispositivos_titulares_titular_id
    FOREIGN KEY (titular_id) REFERENCES TITULARES(id);